### ISSUE TITLE
Variable of generic type?

### ISSUE THREAD

**Issue by jirutka** [tailhook/lithos#13]
According to the [documentation of Container Configuration](https://lithos.readthedocs.io/en/latest/container_config.html#variables) there are only three types of variables – `TcpPort`, `Choice` and `Name` – and all used variables must be declared. I’ve checked also sources and it seems that really only these three types are accepted.

That’s very restricting. I’d like to declare e.g. variable for base URI of the application and use it in `environ` to pass it into the container as environment variable or via arguments. Is this wrong usage of the variables?

**Comment by tailhook** [comment]
Well, any usage of variables might be fine. What I'm trying to avoid is allowing arbitrary code execution:
```
executable: /bin/sh
arguments:
- -c
- "@{variable}"
```

So if you can make a "choice" variable for it (i.e. if you have limited set of base urls), just go for it.

Otherwise, I'm not sure how to make them well-defined. May be allow arbitrary regex validation. Or just allow anything in lithos, but make a lint that disallows arbitrary variables in my own deployments.

Also, your specific context would help: do you want to supply lithos config in on-premise or open-source project, where arbitrary urls are expected? Or is it just to make multiple staging/production systems? Is it really URI or just hostname? Will URI type theoretically help (although, we wouln't want to add a 100 of variable types), or you have other things to tweak? Maybe it's fine for you to just generate a lithos file from a template?

**Comment by jirutka** [comment]
Thank you for very fast response! 😺 

> do you want to supply lithos config in on-premise or open-source project, where arbitrary urls are expected?

It’s for internal project in this case. URI is just one example, I wanted to use it also for URI of DB server, DB password etc.

> Or is it just to make multiple staging/production systems?

This.

> Is it really URI or just hostname?

In this case, it’s really an URI.

> Will URI type theoretically help, or you have other things to tweak?

URI type might be useful, but I’m not sure if this is a good direction… It’d be better to just add generic types such as string, integer, boolean… Actually, YAML already have such types – `!!str`, `!!int`, `!!bool`.

> Maybe it's fine for you to just generate a lithos file from a template?

I can generate it from template. The problem is that container config is inside the image and I don’t wanna hard-coded URIs and password directly in the image (b/c staging/production environments).

**Comment by tailhook** [comment]
> Actually, YAML already have such types – !!str, !!int, !!bool.

These can't be used because they denote value `!!str "something"`   or `!!int 1234`. But that's unimportant.

Important question is how do you generate processes config? How do you deliver (plan to deliver) these variables and secrets to the application?

----

We generate it by orchestrator (verwalter), and important thing to know here is that it shows you all the variables and generated file too. So if there are **secret** variables it isn't good match.

I'm thinking of something like:
```
variables:
  db_password: !SecretVar
environ:
  DB_URL: postgres://user:@{db_password}@db.example.org/dbname
```
And then in sandbox and/or processes config:
```
secrets-file: /etc/my-service/secret-vars.yaml
```

The problem is that it isn't good for your use case too:
1. Not all of your parameters are exactly secrets
2. Some parameters contain secrets like DB_URL above but it might be important to put the actual url to some variable too

We can call it `ExternalVar`  or something like that instead. But then again combining secrets and non-secrets is still a problem.

What do you think?

-----
To give you more context: Currently, we put secrets in a directory and mount it as:
```
volumes: !Readonly /secrets
```
Surely this requires actual application to handle the config, which is too much work for some apps, so I'm willing to change that too.

**Comment by jirutka** [comment]
> Important question is how do you generate processes config? How do you deliver (plan to deliver) these variables and secrets to the application?

We use GitLab and GitLab CI (on our infra, not gitlab.com) for building projects and deployment. Non-secret variables for all environments will be stored in some config inside project’s repository (maybe some of them on the server with Lithos). Secret variables will be in the project’s secret variables (i.e. exported to CI as environment variables).

I can generate Lithos config on CI, execute some commands on the Lithos server via SSH or whatever. Applications may read parameters from a file, environment variables or some of them from CLI arguments.

(I’m on a meeting now, I’ll probably write some feedback for the second part later.)

**Comment by jirutka** [comment]
> Important question is how do you generate processes config? How do you deliver (plan to deliver) these variables and secrets to the application?

We use GitLab and GitLab CI (on our infra, not gitlab.com) for building projects and deployment. Non-secret variables for all environments will be stored in some config inside project’s repository (maybe some of them on the server with Lithos). Secret variables will be in the project’s secret variables (i.e. exported to CI as environment variables).

I can generate Lithos config on CI, execute some commands on the Lithos server via SSH or whatever. Applications may read parameters from a file, environment variables or some of them from CLI arguments.

(I’m on a meeting now, I’ll probably write some feedback for the second part later.)

**Comment by tailhook** [comment]
So your answer sounds like you can also just put secrets in a config file on server and read it in a same way as configuration file: `app --config /container/dir/config.toml --secrets /secrets/secrets.toml`.

Is it okay? Can `secrets-file` solution above help you (i.e. make container config easier)? Should we also simplify/extend non-secret variables too?

**Comment by tailhook** [comment]
Okay, so recent version added `DottedName` which basically means DNS name (or possibly a module or class name). And we also have done #14 for secrets. I'm still hesitant to allow arbitrary strings to prevent injection attacks. We may reconsider this issue later.
