### ISSUE TITLE
Lithos vs Vagga

### ISSUE THREAD

**Issue by kuraga** [tailhook/lithos#9]
Good day, @tailhook !

Tell me, please: how could Lithos be compared with Vagga?

Thanks!

**Comment by tailhook** [comment]
Lithos is a production-grade supervisor for containers. Its task is to run containers and restart them if needed. That's basically it.

Vagga is a development tool. It supports building and versioning containers. As well much richer way to configure and run commands with their dependencies. But is not suited for long-running processes.

The rule of the thumb: lithos is used on servers and vagga is used on workstations and CI.

**Comment by kuraga** [comment]
@tailhook , thanks! But that's I saw in descriptions by myself :smile: 

But technically? Ok, another question: what are there common features? They both can run containers?

Explain: based on that description's **ideas**, I thought that second have to be an extension of first, or vice versa. But it's not...

**Comment by tailhook** [comment]
Yes. They both run containers. They share some libraries. What's different:
1. Lithos runs as root by design (because this is the only way to support some features), vagga runs as user because this is the only way to run arbitrary downloaded project securely
2. Configuration file formats are very different: lithos expects config put into the container with all the environment and parameters set. While vagga reads config first and then starts to build container, and allows to run anything in container (limiting folders which you might use)

I.e. this contrast is enough to make them different products rather than superset of one another. Also lithos is quite small: 5k LoC, mostly parsing configuration and converting it into system calls (but also convenience tools like lithos_clean and lithos_ps). While vagga is bigger because it has to provide all the convenience wrappers around package managers and other build tools.

Does this sound more clear?

**Comment by kuraga** [comment]
Yes, thanks!
